# Generated by Django 4.1.1 on 2022-09-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_audit",
            field=models.BooleanField(default=True),
        ),
    ]
