# Generated by Django 4.1.1 on 2022-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_alter_userprofile_user_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("1", "住户"), ("2", "维修员"), ("3", "管理员")], max_length=6
            ),
        ),
    ]
