# Generated by Django 4.1.1 on 2022-09-23 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apis", "0004_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="charge_type",
            field=models.CharField(
                choices=[("1", "物业费"), ("2", "水费"), ("3", "车位费")],
                default=1,
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="maintainmessage",
            name="maintain_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="maintainmessage",
            name="to_maintenance_men",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_maintenance_men",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="complaintmessage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="maintainmessage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="maintainmessage",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
