# Generated by Django 4.1.1 on 2022-09-24 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apis", "0005_charge_charge_type_maintainmessage_maintain_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("content", models.CharField(max_length=128)),
                ("update_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["update_time"],},
        ),
        migrations.AlterModelOptions(name="carport", options={"ordering": ["id"]},),
        migrations.AlterModelOptions(name="charge", options={"ordering": ["id"]},),
        migrations.AlterModelOptions(
            name="complaintmessage", options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="maintainmessage", options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(name="userprofile", options={"ordering": ["id"]},),
        migrations.AlterField(
            model_name="carport",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carport",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="charge",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charge",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="complaintmessage",
            name="to_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaint",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
