# Generated by Django 4.1.1 on 2022-09-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0006_announcement_alter_carport_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement", options={"ordering": ["-update_time"]},
        ),
        migrations.RemoveField(model_name="maintainmessage", name="to_carport",),
    ]
